timeout 300 '/usr/bin/swaylock -f'
timeout 600 '/usr/bin/niri msg action power-off-monitors' resume '/usr/bin/niri msg action power-on-monitors'
before-sleep '/usr/bin/swaylock -f'
after-resume '/usr/bin/niri msg action power-on-monitors'
